//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HangKenhAppEntities2 : DbContext
    {
        public HangKenhAppEntities2()
            : base("name=HangKenhAppEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NhapDetail> NhapDetails { get; set; }
        public DbSet<Nhapinfo> Nhapinfoes { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<UserLogin> UserLogins { get; set; }
        public DbSet<XuatDetail> XuatDetails { get; set; }
        public DbSet<XuatInfo> XuatInfoes { get; set; }
    }
}
