//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatDetail
    {
        public int Id { get; set; }
        public Nullable<int> XuatId { get; set; }
        public string PhieuYc { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> Trongluong { get; set; }
    }
}
